"""empty message

Revision ID: 18e5593e6caf
Revises: 8a6105287048
Create Date: 2021-08-04 15:54:25.790795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e5593e6caf'
down_revision = '8a6105287048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
