"""empty message

Revision ID: 1b15d14bc102
Revises: 13b5f14d01e2
Create Date: 2021-08-13 11:08:34.569360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b15d14bc102'
down_revision = '13b5f14d01e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
