"""empty message

Revision ID: 6545b432964d
Revises: 1b15d14bc102
Create Date: 2021-08-13 13:20:44.029841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6545b432964d'
down_revision = '1b15d14bc102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('coupon_relation', 'coupon', ['coupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('coupon_relation', type_='foreignkey')
        batch_op.drop_column('discount')
        batch_op.drop_column('coupon_id')

    # ### end Alembic commands ###
