"""empty message

Revision ID: c929c56b0a75
Revises: 6545b432964d
Create Date: 2021-08-13 14:40:56.278698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c929c56b0a75'
down_revision = '6545b432964d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
